apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-volume
spec:
  storageClassName: nginx-sc-example
  capacity:
    storage: 10Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/data" 